<template>
  <div class="about">
    <h1>WikiGen</h1>
    <p>
      My name is <strong>Sidney Kingsley</strong>, and I am a final year student
      at the <a href="https://www.plymouth.ac.uk/">University of Plymouth</a>.
      WikiGen is my project for the DAT611 module of my course,
      <a
        href="https://www.plymouth.ac.uk/courses/undergraduate/bsc-digital-media-design"
      >
        Digital Media Design
      </a>
      (BSc).
    </p>
    <p>
      WikiGen is a single page web application with the aim of utilising machine
      learning (ML) technologies to create personalised, intelligent, and unique
      biography-style articles for the people that use it.
    </p>
    <h2>ML Technologies</h2>
    <p>
      This project uses
      <a href="http://karpathy.github.io/2015/05/21/rnn-effectiveness/">
        CharRNN</a
      >, a character-based recurrent neural network, to generate a sequence of
      characters in a style learned from a corpus of text. CharRNN is of the
      multi-layer LSTM architecture. This acronym stands for long-short-term
      memory, and expresses the way this neural network works: the network
      analyses the sequence of characters before and predicts the next
      character, this process can then be repeated infinite times. While this is
      an incredibly effective technique, this short-term, recurrent approach,
      explains why there is sometimes a lack of greater context to the words and
      sentences that are generated by this CharRNN model.
    </p>
    <p>
      To generate text with CharRNN on the web, this project uses
      <a href="https://ml5js.org/">ML5.js</a>, an open-source interface for
      <a href="https://www.tensorflow.org/">TensorFlow.js</a>. TensorFlow.js is
      a JavaScript library used to train and deploy ML models in the browser
      using WebGL.
    </p>
    <h2>Data Collection</h2>
    <p>
      The data the RNN used in this project has been trained on has all been
      scraped from <a href="https://wikipedia.org/">Wikipedia</a>. While
      Wikipedia openly allows and encourages collaboration and redistribution of
      its data, some information featured in this project may be copyrighted.<a
        href="#refs"
      >
        <sup>[1]</sup>
      </a>
      None of the data scraped for this project will be profited from in any
      way.
    </p>
    <p>
      It is worth noting that while the individual articles that have scraped
      for this project have been chosen by outside sources and an attempt at
      excluding personal bias has been made, bias will still be present in this
      project. A significant source of this bias will be from the nature of
      Wikipedia as a data source itself. Wikipedia is an online encyclopaedia
      which includes biographies of notable people, ‘notable’ being the key word
      here. The database used in this project cannot be free from bias as it
      does not represent all people, just people that are considered
      extraordinary and notable, many of these people may also have been propped
      up by a level of privilege not widely shared with the general population.
      Choices made by the Wikipedia editors and the site
      <a href="https://www.behindthename.com/namesakes/">Behind The Name</a>
      (the collection of various categories of notable people used to identify
      the articles scraped in this project), will be burdened with these
      people’s individual biases.
    </p>
    <p>
      Hopefully, the potentially biased results of this generative project can
      be taken with caution and will not overshadow the demonstrated
      significance of this technology or subtract from the enjoyment of its
      strange creations.
    </p>
    <h2 id="refs">References</h2>
    <ol class="ref">
      <li>
        “Wikipedia:Reusing Wikipedia content” Wikipedia, Wikimedia Foundation,
        29 July 2019,
        <a
          href="https://en.wikipedia.org/wiki/Wikipedia:Reusing_Wikipedia_content"
          >en.wikipedia.org/wiki/Wikipedia:Reusing_Wikipedia_content</a
        >.
      </li>
    </ol>
  </div>
</template>

<script>
export default {}
</script>

<style scoped>
.about {
  padding: 30px 35px;
}
.about h1 {
  font-family: LL-d, 'Linux Libertine', 'Georgia', 'Times', serif;
  font-size: 34px;
  border-bottom: 1px solid #a2a9b1;
  line-height: 1.4;
  margin-bottom: 10px;
}
.about h2 {
  font-family: LL-d, 'Georgia', 'Times', serif;
  font-size: 24px;
  border-bottom: 1px solid #a2a9b1;
  margin-top: 15px;
  /* margin-bottom: -15px; */
  line-height: 1.3;
  margin-bottom: 5px;
}
.about p {
  font-size: 15px;
  font-family: sans-serif;
  line-height: 1.6;
  padding-bottom: 5px;
}
.about p strong {
  font-size: 15px;
  font-family: sans-serif;
  line-height: 1.6;
}
.about p a {
  font-size: 15px;
  font-family: sans-serif;
  line-height: 1.6;
  color: var(--links);
  text-decoration: none;
}
.about p a:hover {
  text-decoration: underline;
}
.about p sup {
  color: var(--links);
  font-family: sans-serif;
  line-height: 1.1;
}
.about .ref {
  max-width: 300px;
  word-wrap: break-word;
  padding-top: 5px;
}
.about li {
  font-size: 15px;
  font-family: sans-serif;
  line-height: 1.4;
  padding-bottom: 5px;
}
.about ol {
  margin-left: 20px;
}
.about li a {
  font-size: 15px;
  font-family: sans-serif;
  color: var(--links);
  text-decoration: none;
}

.section-heading {
  font-family: LL-d, 'Linux Libertine', 'Georgia', 'Times', serif;
  font-size: 32px;
  border-bottom: 1px solid #a2a9b1;
  line-height: 1.4;
  margin: 10px 30px 5px 30px;
}
.tag-text {
  line-height: 1.6;
  font-size: 13px;
  margin: 0px 30px 10px 30px;
  line-height: 1.5;
}
.gen-text {
  white-space: pre-wrap;
  margin: 0 30px;
  font-size: 15px;
  font-family: sans-serif;
  line-height: 1.6;
  padding-bottom: 50px;
}
.gen-text h2 {
  font-family: LL-d, 'Georgia', 'Times', serif;
  font-size: 24px;
  border-bottom: 1px solid #a2a9b1;
  margin-top: 15px;
  margin-bottom: -15px;
  text-transform: lowercase;
  line-height: 1.3;
}
.gen-text h2::first-letter {
  text-transform: uppercase;
}
.gen-text sup {
  color: #0645ad;
}
</style>
